# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - master

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -e SC1091 -e SC2002 -e SC2015 -e SC2086 -e SC2034

